config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('content/', include('content.urls', namespace='content')),
    path('pay/', include('payment.urls', namespace='payment')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from .views import PostCreateView, PostUpdateView, PostDetailView, PostDeleteView
from .views import VideoCreateView, VideoUpdateView, VideoDetailView, VideoDeleteView, FeedListView
from .apps import ContentConfig

app_name = ContentConfig.name

urlpatterns = [
    path('post/create/', PostCreateView.as_view(), name='post-create'),
    path('video/create/', VideoCreateView.as_view(), name='video-create'),
    path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='post-update'),
    path('video/update/<slug:slug>/', VideoUpdateView.as_view(), name='video-update'),
    path('post/detail/<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('video/detail/<slug:slug>/', VideoDetailView.as_view(), name='video-detail'),
    path('post/delete/<slug:slug>', PostDeleteView.as_view(), name='post-delete'),
    path('video/delete/<slug:slug>', VideoDeleteView.as_view(), name='video-delete'),
    path('feed/', FeedListView.as_view(), name='feed'),
]

payment/urls.py
from django.urls import path
from payment.apps import PaymentConfig
from .views import SubscribeToAuthor, PaymentCreateView, webhook, PayOfferView, UserSubscriptionList

app_name = PaymentConfig.name

urlpatterns = [
    path('subscribe-author/', SubscribeToAuthor.as_view(), name='subscribe_author'),
    path('subscribers-list/', UserSubscriptionList.as_view(), name='subscribers_list'),
    path('pay/', PaymentCreateView.as_view(), name='pay'),
    path('offer/', PayOfferView.as_view(), name='pay_offer'),
    path('webhook/', webhook, name='webhook'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from .views import IndexView, UserCreateView, LoginView, ConfirmCodeView, AuthorListView, AuthorCreateView, ProfileView, \
    ProfileUpdateView, AuthorDetailView, UserSetPasswordView, AuthorProfileView, AuthorProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', UserCreateView.as_view(), name='login'),
    path('signin/', LoginView.as_view(), name='signin'),
    path('confirm_code/', ConfirmCodeView.as_view(), name='confirm_code'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('flag-autor/', AuthorCreateView.as_view(), name='flag-autor'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('author-profile/', AuthorProfileView.as_view(), name='author_profile'),
    path('author-profile/update/', AuthorProfileUpdateView.as_view(), name='profile_author_update'),
    path('set-password/', UserSetPasswordView.as_view(), name='set_password'),
    path('blogger/list/', AuthorListView.as_view(), name='list'),
    path('author-profile/<slug:slug>', AuthorDetailView.as_view(), name='author_profile'),
]

users/models.py
import uuid
from django.core.validators import MaxValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    phone_number = models.CharField(max_length=10, unique=True, verbose_name='Номер телефона')
    email = models.EmailField(verbose_name='Email', **NULLABLE)
    avatar = models.ImageField(upload_to='avatars/', verbose_name='Аватар', **NULLABLE)
    is_author = models.BooleanField(default=False, verbose_name='Признак авторства')

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = []


class Author(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)
    blog_name = models.CharField(max_length=35, verbose_name='Название блога')
    slug = models.CharField(max_length=50, unique=True, verbose_name='Слаг', **NULLABLE)
    blog_description = models.TextField(verbose_name='Описание блога')
    subscription_price = models.PositiveSmallIntegerField(verbose_name='Стоимость подписки',
                                                          validators=[MaxValueValidator(9999)])

    def __str__(self):
        return f'{self.blog_name} - {self.subscription_price}'

    class Meta:
        verbose_name = 'автор'
        verbose_name_plural = 'авторы'

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, SetPasswordForm
from common.mixins import StylesMixin
from users.models import User, Author
from django import forms


class UserForm(StylesMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('phone_number',)

    def is_valid(self):
        valid = super().is_valid()
        if 'phone_number' in self.errors:
            unique_error = 'Пользователь с таким Номер телефона уже существует.'
            if unique_error in self.errors['phone_number']:
                del self.errors['phone_number']
                self.cleaned_data['phone_number'] = self.data['phone_number']
                return True
        return valid

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if not phone_number.isdigit():
            raise forms.ValidationError('Номер телефона должен содержать только цифры.')
        if len(phone_number) != 10:
            raise forms.ValidationError('Номер телефона должен содержать ровно 10 цифр.')
        return phone_number


class LoginForm(StylesMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = ('phone_number', 'password')


class ConfirmCodeForm(StylesMixin, forms.Form):
    confirm_code = forms.CharField(max_length=6, help_text='Введите шестизначный код из смс сообщения')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean_confirm_code(self):
        user_code = self.cleaned_data['confirm_code']
        confirm_code = self.request.session['confirm_code']
        if str(user_code) != str(confirm_code):
            raise forms.ValidationError('Неверный код подтверждения')
        return confirm_code


class CreateAuthorForm(StylesMixin, forms.ModelForm):
    class Meta:
        model = Author
        fields = ('blog_name', 'blog_description', 'subscription_price')

    def clean_blog_name(self):
        blog_name = str(self.cleaned_data['blog_name'])
        if not self.instance.blog_name == blog_name:
            if Author.objects.filter(blog_name=blog_name).exists():
                raise forms.ValidationError('Это название блога занято')
        if len(blog_name) < 3:
            raise forms.ValidationError('Название блога не может быть меньше 3 символов')
        return blog_name

    def clean_blog_description(self):
        blog_description = str(self.cleaned_data['blog_description'])
        if len(blog_description) < 20:
            raise forms.ValidationError('Описание блога не может быть меньше 20 символов')
        return blog_description


class ProfileUpdateForm(StylesMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserSetPasswordForm(StylesMixin, SetPasswordForm):
    class Meta:
        fields = ('new_password1', 'new_password2')

users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from common.mixins import SlugifyMixin, TitleMixin, AuthorRequiredMixin, NotLoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, FormView, ListView, DetailView, UpdateView
from django.contrib.auth.views import LoginView as BaseLoginView
from .forms import UserForm, LoginForm, ConfirmCodeForm, CreateAuthorForm, ProfileUpdateForm, UserSetPasswordForm
from .services import get_confirm_code, send_sms_code
from content.models import Post, Video
from .models import User, Author


class GetContextDataMixin(DetailView):
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        author = self.get_object()
        posts = Post.objects.filter(author=author).values()
        videos = Video.objects.filter(author=author).values()
        for post_dict in posts:
            post_dict['type'] = 'post'
        combined_data = sorted(list(posts) + list(videos), key=lambda x: x['created_at'], reverse=True)
        context_data['object_list'] = combined_data
        context_data['title'] = f'Профиль {author.blog_name}'
        return context_data


class IndexView(TitleMixin, TemplateView):
    template_name = 'users/index.html'
    title = 'Главная'


class UserCreateView(TitleMixin, NotLoginRequiredMixin, CreateView):
    template_name = 'users/phone_signin.html'
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:confirm_code')
    title = 'Вход'

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            phone_number = form.cleaned_data['phone_number']
            confirm_code = get_confirm_code()
            send_sms_code(phone_number=phone_number, confirm_code=confirm_code)
            User.objects.get_or_create(phone_number=phone_number)
            self.request.session['phone_number'] = phone_number
            self.request.session['confirm_code'] = confirm_code
            return HttpResponseRedirect(self.success_url)
        else:
            return self.form_invalid(form)


class LoginView(TitleMixin, NotLoginRequiredMixin, BaseLoginView):
    template_name = 'users/password_signin.html'
    form_class = LoginForm
    title = 'Вход'


class ConfirmCodeView(TitleMixin, NotLoginRequiredMixin, FormView):
    form_class = ConfirmCodeForm
    template_name = 'users/confirm_code.html'
    success_url = reverse_lazy('users:list')
    title = 'Подтверждение номера'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            phone_number = self.request.session['phone_number']
            user = User.objects.filter(phone_number=phone_number).first()
            login(self.request, user)
            del self.request.session['confirm_code']
            del self.request.session['phone_number']
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def get(self, request, *args, **kwargs):
        context_data = self.get_context_data()
        if 'resend' in request.GET:
            phone_number = request.session['phone_number']
            confirm_code = get_confirm_code()
            self.request.session['confirm_code'] = confirm_code
            send_sms_code(phone_number, confirm_code)
        return self.render_to_response(context_data)


class ProfileView(TitleMixin, LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/profile.html'
    title = 'Профиль'

    def get_object(self, queryset=None):
        return self.request.user


class ProfileUpdateView(TitleMixin, LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileUpdateForm
    template_name = 'users/update_profile.html'
    success_url = reverse_lazy('users:profile')
    title = 'Редактирование профиля'

    def get_object(self, queryset=None):
        return self.request.user


class AuthorCreateView(TitleMixin, LoginRequiredMixin, SlugifyMixin, CreateView):
    form_class = CreateAuthorForm
    model = Author
    template_name = 'users/author_form.html'
    success_url = reverse_lazy('users:list')
    title = 'Стать автором'

    def form_valid(self, form):
        if form.is_valid():
            user = self.request.user
            author = form.save()
            author.user = user
            author.slug = self.get_unique_slug(author.blog_name)
            user.is_author = True
            author.save()
            user.save()
        return super().form_valid(form)


class AuthorListView(TitleMixin, ListView):
    model = Author
    template_name = 'users/author_list.html'
    title = 'Блогеры'

    def get_queryset(self):
        user = self.request.user
        if user.is_author if user.is_authenticated else False:
            queryset = Author.objects.exclude(id=user.author.id)
        else:
            queryset = Author.objects.all()
        return queryset


class AuthorDetailView(GetContextDataMixin):
    model = Author
    template_name = 'users/author_detail.html'


class UserSetPasswordView(TitleMixin, LoginRequiredMixin, FormView):
    form_class = UserSetPasswordForm
    template_name = 'users/set_password.html'
    success_url = reverse_lazy('users:profile')
    title = 'Установление пароля'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class AuthorProfileView(TitleMixin, AuthorRequiredMixin, GetContextDataMixin):
    model = Author
    template_name = 'users/author_profile.html'
    title = 'Профиль автора'

    def get_object(self, queryset=None):
        return Author.objects.filter(user=self.request.user).first()


class AuthorProfileUpdateView(TitleMixin, AuthorRequiredMixin, UpdateView):
    model = User
    form_class = CreateAuthorForm
    template_name = 'users/update_author_profile.html'
    success_url = reverse_lazy('users:author_profile')
    title = 'Редактирование профиля автора'

    def get_object(self, queryset=None):
        return Author.objects.filter(user=self.request.user).first()

users/templates/users/author_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<main class="container mt-3">
    <div class="card my-4 mx-auto">
        <div class="card-body m-2 m-md-4">
            <article class="row">
                <div class="col-5"><img src="{{ object.user.avatar|my_avatar }}" tyle="width: 450px; height: 450px;"
                                        class="img-fluid" alt=""></div>
                <div class="col-7">

                    <section class="teacher=info">
                        <h1 class="h2">{{ object.blog_name }}</h1>
                        <p style="text-align: justify;">{{ object.blog_description }}</p>
                        <p class="text-end"><span class="badge badge-secondary mr-2">Для путешествий </span>Стоимость
                            подписки: {{ object.subscription_price }} / мес.</p>
                        <div class="d-flex justify-content-end align-items-end" style="height: 50px;">
                            {% if request.user.is_authenticated %}
                            <form action="{% url 'payment:subscribe_author' %}" method="post">
                                <input type="hidden" name="author_id" value="{{ object.id }}">
                                {% else %}
                                <form action="{% url 'users:login' %}" method="get">
                                    {% endif %}
                                    {% csrf_token %}
                                    {% if request.user.is_authenticated %}
                                    {% is_subscribed request.user object as subscription_status %}
                                    {% if subscription_status %}
                                    <button class="btn btn-outline-danger btn-sm mr-3 mx-2" type="submit">
                                        Отписаться
                                    </button>
                                    {% else %}
                                    <button class="btn btn-outline-success btn-sm mr-3 mx-2" type="submit">
                                        Подписаться
                                    </button>
                                    {% endif %}
                                    {% endif %}
                                </form>
                                {% if request.user.is_authenticated %}
                                <form action="{% url 'payment:pay' %}" method="post">
                                    <input type="hidden" name="author_id" value="{{ object.id }}">
                                    {% else %}
                                    <form action="{% url 'users:login' %}" method="get">
                                        {% endif %}
                                        {% csrf_token %}
                                        <button class="btn btn-outline-primary btn-sm mr-3 mx-2" type="submit">
                                            Купить подписку
                                        </button>
                                    </form>
                        </div>
                    </section>
                </div>
            </article>
        </div>
    </div>
    {% if not object_list %}
    <h1 class="h1 text-center w-50 mx-auto mt-1 py-5 mb-4"><strong>У автора пока нет публикаций</strong></h1>
    {% else %}
    <h1 class="h1 text-center w-50 mx-auto mt-1 py-5 mb-4"><strong>Лента:</strong></h1>
    {% for obj in object_list %}
    <div class="pc-container" style="background-image: url('/media/{{ obj.imagine }}');">
        <div class="pc-cover">
            <div class="pc-header">
                {% if obj.type == 'post' %}
                <h2 class="pc-title"><a href="{% url 'content:post-detail' obj.slug %}" class="pc-link">
                    {{ obj.title }}</a></h2>
                {% else %}
                <h2 class="pc-title"><a href="{% url 'content:video-detail' obj.slug %}" class="pc-link">
                    {{ obj.title }}</a></h2>
                {% endif %}
                <p class="pc-description">{{ obj.body|truncatechars:150 }}</p>
            </div>
            <div class="pc-footer">
                <span class="pc-date">{{ obj.created_at|date }} в {{ obj.created_at|time }}</span>
                {% if obj.type == 'post' %}
                <a href="{% url 'content:post-detail' obj.slug %}" class="pc-more-btn">Подробнее</a>
                {% else %}
                <a href="{% url 'content:video-detail' obj.slug %}" class="pc-more-btn">Подробнее</a>
                {% endif %}

            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</main>
{% endblock %}

users/templates/users/author_form.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<main class="form-signin w-100 m-auto">
    <div class="container">
        <div class="row row-centered">
            <div class="col-4 mt-5 mx-auto">
                <form method="post">
                    {% csrf_token %}
                    <h2 class="h2 mb-3 fw-normal text-center">{{ title }}</h2>
                    <div class="input-group input-group-lg mb-3">
                        {{ form.blog_name|add_placeholder:'Название блога' }}
                    </div>
                    <div class="input-group input-group-lg mb-3">
                        {{ form.blog_description|add_placeholder:'Описание блога' }}
                    </div>
                    <div class="input-group input-group-lg mb-3">
                        {{ form.subscription_price|add_placeholder:'Стоимость подписки/мес' }}
                    </div>
                    <br>
                    {{ form.blog_name.errors }}
                    {{ form.blog_description.errors }}
                    {{ form.subscription_price.errors }}
                    {% if form.errors %}
                    <br>
                    {% endif %}
                    <button class="btn btn-primary w-100 py-2" type="submit">Стать автором</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/author_list.html
{% extends 'base.html' %}
{% load users_tags %}
{% load my_tags %}
{% block content %}
<main class="container mt-3">
    <h1 class="h1 text-center w-50 mx-auto mt-1 py-5 mb-4"><strong>Все авторы:</strong></h1>


    <div class="row">
        <div class="col-12 col-lg-10 offset-lg-1 m-auto">
            {% for object in object_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-3"><img src="{{ object.user.avatar|my_avatar }}"
                                                class="img-fluid rounded-circle border"
                                                style="width: auto; height: 200px;" alt=""></div>
                        <div class="col-9">
                            <p class="text-end">Стоимость подписки: {{ object.subscription_price }} / мес</p>
                            <h2 class="h4">{{ object.blog_name }}</h2>
                            <p style="text-align: justify;">{{ object.blog_description|truncatechars:150 }}</p>
                            <div class="d-flex justify-content-end align-items-end" style="height: 100px;">
                                {% if request.user.is_authenticated %}
                                <form action="{% url 'payment:subscribe_author' %}" method="post">
                                    <input type="hidden" name="author_id" value="{{ object.id }}">
                                    {% else %}
                                    <form action="{% url 'users:login' %}" method="get">
                                        {% endif %}
                                        {% csrf_token %}
                                        {% if request.user.is_authenticated %}
                                        {% is_subscribed request.user object as subscription_status %}
                                        {% if subscription_status %}
                                        <button class="btn btn-outline-danger btn-sm mr-3 mx-2" type="submit">
                                            Отписаться
                                        </button>
                                        {% else %}
                                        <button class="btn btn-outline-success btn-sm mr-3 mx-2" type="submit">
                                            Подписаться
                                        </button>
                                        {% endif %}
                                        {% endif %}
                                    </form>
                                    <a href="{% url 'users:author_profile' object.slug %}"
                                       class="btn btn-outline-primary btn-sm mr-3 mx-2">Показать
                                        информацию</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/author_profile.html
{% extends 'base.html' %}
{% load my_tags %}
{% load users_tags %}
{% block content %}
<main class="container mt-3">
    <div class="row">
        <div style="text-align:center; margin-top:20px" class="col-lg-6 mx-auto">
            <img style="width:300px; height:300px; margin:auto;" class="bd-placeholder-img rounded-circle border"
                 src="{{ object.user.avatar|my_avatar }}">
            <h2 class="fw-normal">{{ object.blog_name }}</h2>
            <a style="margin-top: 10px;" class="btn btn-secondary mx-2" href="{% url 'users:profile_author_update' %}">Редактировать
                профиль автора</a>
        </div>
    </div>
    {% if not object_list %}
    <h1 class="h1 text-center w-50 mx-auto mt-1 py-5 mb-4"><strong>У вас пока нет публикаций</strong></h1>
    {% else %}
    <h1 class="h1 text-center w-50 mx-auto mt-1 py-5 mb-4"><strong>Ваши публикации:</strong></h1>
    {% for obj in object_list %}
    <div class="pc-container" style="background-image: url('/media/{{ obj.imagine }}');">
        <div class="pc-cover">
            <div class="pc-header">
                {% if obj.type == 'post' %}
                <h2 class="pc-title"><a href="{% url 'content:post-detail' obj.slug %}" class="pc-link">
                    {{ obj.title }}</a></h2>
                {% else %}
                <h2 class="pc-title"><a href="{% url 'content:video-detail' obj.slug %}" class="pc-link">
                    {{ obj.title }}</a></h2>
                {% endif %}
                <p class="pc-description">{{ obj.body|truncatechars:150 }}</p>
            </div>
            <div class="pc-footer">
                <span class="pc-date">{{ obj.created_at|date }} в {{ obj.created_at|time }}</span>
                {% if obj.type == 'post' %}
                <a href="{% url 'content:post-delete' obj.slug %}" class="button unsubscribe">Удалить</a>
                <a href="{% url 'content:post-update' obj.slug %}" class="pc-more-btn">Редактировать</a>
                {% else %}
                <a href="{% url 'content:video-delete' obj.slug %}" class="button unsubscribe">Удалить</a>
                <a href="{% url 'content:video-update' obj.slug %}" class="pc-more-btn">Редактировать</a>
                {% endif %}

            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</main>
{% endblock %}

users/templates/users/index.html
{% extends 'base.html' %}
{% block content %}
<section class="welcome">
    <h1>Добро пожаловать на BoostContent!</h1>
    <p>Откройте для себя лучшие статьи, рассказы и публикации от талантливых авторов со всего мира.</p>
</section>

<section class="call-to-action">
    <h2>Готовы поделиться своими историями?</h2>
    <p>Присоединяйтесь к нашему сообществу творческих людей уже сегодня.</p>
    {% if request.user.is_authenticated %}
    {% if request.user.is_author %}
    <a href="{% url 'users:author_profile' %}" class="btn btn-outline-dark mr-3 mx-2">Начать публиковаться</a>
    {% else %}
    <a href="{% url 'users:flag-autor' %}" class="btn btn-outline-dark mr-3 mx-2">Начать публиковаться</a>
    {% endif %}
    {% else %}
    <a href="{% url 'users:login' %}" class="btn btn-outline-dark mr-3 mx-2">Начать публиковаться</a>
    {% endif %}
</section>
{% endblock %}

users/templates/users/password_signin.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<main class="form-signin w-100 m-auto">
    <div class="container">
        <div class="row row-centered">
            <div class="col-4 mt-5 mx-auto">
                <form method="post">
                    {% csrf_token %}
                    <h2 class="h2 mb-3 fw-normal text-center">Вход</h2>
                    <div class="input-group input-group-lg mb-3">
                        <span class="input-group-text" id="phone-number-addon1">+7</span>
                        {{ form.username|add_placeholder:'Телефон' }}
                    </div>
                    <div class="input-group input-group-lg mb-3">
                        {{ form.password|add_placeholder:'Пароль' }}
                    </div>
                    <br>
                    <button class="btn btn-primary w-100 py-2" type="submit">Войти</button>
                </form>
                <div class="mt-4">
                    <p class="text-center"><a class="link-opacity-100-hover" href="{% url 'users:login' %}">Войти по
                        коду из телефона</a></p>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/phone_signin.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<main class="form-signin w-100 m-auto">
    <div class="container">
        <div class="row row-centered">
            <div class="col-4 mt-5 mx-auto">
                <form method="post">
                    {% csrf_token %}
                    <h2 class="h2 mb-3 fw-normal text-center">Вход</h2>
                    <div class="input-group input-group-lg mb-3">
                        <span class="input-group-text" id="phone-number-addon1">+7</span>
                        {{ form.phone_number|add_placeholder:'Телефон' }}
                    </div>
                    <br>
                    {{ form.phone_number.errors }}
                    {% if form.phone_number.errors %}
                    <br>
                    {% endif %}
                    <button class="btn btn-primary w-100 py-2" type="submit">Получить код на телефон</button>
                </form>
                <div class="mt-4">
                    <p class="text-center"><a class="link-opacity-100-hover" href="{% url 'users:signin' %}">Войти с
                        помощью пароля</a></p>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load my_tags %}
{% load users_tags %}
{% block content %}
<div class="row">
    <div style="text-align:center; margin-top:20px" class="col-lg-6 mx-auto">
        <img style="width:300px; height:300px; margin:auto;" class="bd-placeholder-img rounded-circle border"
             src="{{ object.avatar|my_avatar }}">
        {% if object.first_name and object.last_name %}
        <h2 class="fw-normal">{{ object.first_name }} {{ object.last_name }}</h2>
        {% else %}
        <h2 class="fw-normal">+7 {{ object.phone_number|format_phone }}</h2>
        {% endif %}
        <a style="margin-top: 10px;" class="btn btn-secondary mx-2" href="{% url 'users:profile_update' %}">Редактировать
            профиль</a>
        {% if not request.user.password %}
        <a style="margin-top: 10px;" class="btn btn-secondary mx-2" href="{% url 'users:set_password' %}">Установить пароль</a>
        {% endif %}
    </div>
</div>
{% endblock %}

users/templates/users/set_password.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<main class="form-signin w-100 m-auto">
    <div class="container">
        <button class="btn btn-dark mt-5" onclick="window.history.back();">Назад</button>
        <div class="row row-centered">
            <div class="col-4 mt-5 mx-auto">
                <form method="post">
                    {% csrf_token %}
                    <h2 class="h2 mb-3 fw-normal text-center">{{ title }}</h2>
                    <div class="input-group input-group-lg mb-3">
                        {{ form.new_password1|add_placeholder:'Пароль' }}
                    </div>
                    <div class="input-group input-group-lg mb-3">
                        {{ form.new_password2|add_placeholder:'Повторите пароль' }}
                    </div>
                    <br>
                    <button class="btn btn-primary w-100 py-2" type="submit">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}