config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('content/', include('content.urls', namespace='content')),
    path('pay/', include('payment.urls', namespace='payment')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from .views import PostCreateView, PostUpdateView, PostDetailView, PostDeleteView
from .views import VideoCreateView, VideoUpdateView, VideoDetailView, VideoDeleteView, FeedListView
from .apps import ContentConfig

app_name = ContentConfig.name

urlpatterns = [
    path('post/create/', PostCreateView.as_view(), name='post-create'),
    path('video/create/', VideoCreateView.as_view(), name='video-create'),
    path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='post-update'),
    path('video/update/<slug:slug>/', VideoUpdateView.as_view(), name='video-update'),
    path('post/detail/<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('video/detail/<slug:slug>/', VideoDetailView.as_view(), name='video-detail'),
    path('post/delete/<slug:slug>', PostDeleteView.as_view(), name='post-delete'),
    path('video/delete/<slug:slug>', VideoDeleteView.as_view(), name='video-delete'),
    path('feed/', FeedListView.as_view(), name='feed'),
]

payment/urls.py
from django.urls import path
from payment.apps import PaymentConfig
from .views import SubscribeToAuthor, PaymentCreateView, webhook, PayOfferView, UserSubscriptionList

app_name = PaymentConfig.name

urlpatterns = [
    path('subscribe-author/', SubscribeToAuthor.as_view(), name='subscribe_author'),
    path('subscribers-list/', UserSubscriptionList.as_view(), name='subscribers_list'),
    path('pay/', PaymentCreateView.as_view(), name='pay'),
    path('offer/', PayOfferView.as_view(), name='pay_offer'),
    path('webhook/', webhook, name='webhook'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from .views import IndexView, UserCreateView, LoginView, ConfirmCodeView, AuthorListView, AuthorCreateView, ProfileView, \
    ProfileUpdateView, AuthorDetailView, UserSetPasswordView, AuthorProfileView, AuthorProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', UserCreateView.as_view(), name='login'),
    path('signin/', LoginView.as_view(), name='signin'),
    path('confirm_code/', ConfirmCodeView.as_view(), name='confirm_code'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('flag-autor/', AuthorCreateView.as_view(), name='flag-autor'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('author-profile/', AuthorProfileView.as_view(), name='author_profile'),
    path('author-profile/update/', AuthorProfileUpdateView.as_view(), name='profile_author_update'),
    path('set-password/', UserSetPasswordView.as_view(), name='set_password'),
    path('blogger/list/', AuthorListView.as_view(), name='list'),
    path('author-profile/<slug:slug>', AuthorDetailView.as_view(), name='author_profile'),
]

templates/base.html
{% load static %}
{% load my_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/my_styles.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'imagine/favicon.ico' %}">
</head>
<body class="d-flex flex-column min-vh-100">
<header class="p-3 text-bg-dark">
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <div class="col-md-3 mb-2 mb-md-0">
                <a class="navbar-brand" href="{% url 'users:index' %}">BoostContent</a>
            </div>
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'users:index' %}" class="nav-link px-2 text-white">Главная</a></li>
                <li><a href="{% url 'users:list' %}" class="nav-link px-2 text-white">Блогеры</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'content:feed' %}" class="nav-link px-2 text-white">Лента</a></li>
                <li><a href="{% url 'payment:subscribers_list' %}" class="nav-link px-2 text-white">Мои подписки</a>
                </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
            {% if not user.is_author %}
            <a href="{% url 'users:flag-autor' %}" class="btn btn-warning">Стать автором</a>
            {% else %}
            <div class="dropdown text-end">
                <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="/static/imagine/plus.svg" alt="mdo" width="32" height="32" class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small">
                    <li><a class="dropdown-item" href="{% url 'content:post-create' %}">Новый пост</a></li>
                    <li><a class="dropdown-item" href="{% url 'content:video-create' %}">Новое видео</a></li>
                </ul>
            </div>
            {% endif %}
            <div class="dropdown text-end">
                <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    {% user_avatar as avatar_url %}
                    <img src="{{ avatar_url|my_avatar }}" alt="mdo" width="32" height="32" class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small">
                    {% if request.user.is_author %}
                    <li><a class="dropdown-item" href="{% url 'users:author_profile' %}">Профиль автора</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <li>
                            <button type="submit" class="dropdown-item"
                            >Выход
                            </button>
                        </li>
                    </form>
                </ul>
            </div>
            {% else %}
            <div class="col-md-3 text-end">
                <a href="{% url 'users:login' %}" class="btn btn-outline-light me-2">Войти</a>
            </div>
            {% endif %}
        </header>
    </div>
</header>
{% block content %}
{% endblock %}
<div class="wrapper flex-grow-1"></div>
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top mx-auto">
        <p class="col-md-4 mb-0 text-body-secondary">&copy; 2023 - {% now 'Y' %} BoostContent, Inc</p>

        <a href="/"
           class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <svg class="bi me-2" width="40" height="32">
                <use xlink:href="#bootstrap"/>
            </svg>
        </a>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="{% url 'users:index' %}"
                                    class="nav-link px-2 text-body-secondary">Главная</a></li>
            <li class="nav-item"><a href="{% url 'users:list' %}" class="nav-link px-2 text-body-secondary">Блогеры</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'content:feed' %}" class="nav-link px-2 text-body-secondary">Лента</a></li>
            <li class="nav-item"><a href="{% url 'payment:subscribers_list' %}" class="nav-link px-2 text-body-secondary">Мои подписки</a></li>
            {% endif %}
        </ul>
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>